import { AffinityInfo, Spell, ShopItem, Achievement } from './types';

export const MAGIC_AFFINITIES: Record<string, AffinityInfo> = {
  fire: {
    id: 'fire',
    name: 'นักเวทธาตุไฟ',
    title: 'Pyro Master',
    color: '#f97316',
    badgeBg: 'from-orange-600 to-red-700',
    iconName: 'Flame',
    description: 'มีความเชี่ยวชาญด้านพลังทำลายล้างที่รุนแรง เผาผลาญศัตรูด้วยเปลวเพลิงศักดิ์สิทธิ์',
    baseStats: { atk: 35, def: 15, mp: 100, manaRegen: 8 },
    specialSkill: 'Crimson Burst (+25% ATK Damage)',
    startingSpellId: 'fireball',
    avatarIcon: '🔥',
  },
  water: {
    id: 'water',
    name: 'นักเวทธาตุน้ำ',
    title: 'Aqua Seer',
    color: '#06b6d4',
    badgeBg: 'from-cyan-600 to-blue-700',
    iconName: 'Droplet',
    description: 'พลิ้วไหวและเยือกเย็น สายธารแห่งมนตราฟื้นฟูพลังและแช่แข็งศัตรูในพริบตา',
    baseStats: { atk: 22, def: 25, mp: 130, manaRegen: 15 },
    specialSkill: 'Ocean Sanctuary (+30% MP Regen)',
    startingSpellId: 'icespike',
    avatarIcon: '💧',
  },
  wind: {
    id: 'wind',
    name: 'นักเวทธาตุลม',
    title: 'Gale Sage',
    color: '#10b981',
    badgeBg: 'from-emerald-500 to-teal-700',
    iconName: 'Wind',
    description: 'ว่องไวและอิสระ ดุจสายลมแห่งพายุ คมเวทตัดเฉือนภัยคุกคามด้วยความเร็วแสง',
    baseStats: { atk: 28, def: 18, mp: 110, manaRegen: 12 },
    specialSkill: 'Swift Haste (-20% Spell Cooldown)',
    startingSpellId: 'windblade',
    avatarIcon: '🌪️',
  },
  earth: {
    id: 'earth',
    name: 'นักเวทธาตุดิน',
    title: 'Terra Guard',
    color: '#84cc16',
    badgeBg: 'from-amber-700 to-stone-800',
    iconName: 'Mountain',
    description: 'แข็งแกร่งดั่งขุนเขา ปราการหินโบราณต้านทานความเสียหายทุกประเภท',
    baseStats: { atk: 20, def: 35, mp: 90, manaRegen: 10 },
    specialSkill: 'Stone Citadel (+40% DEF Shield)',
    startingSpellId: 'thunder',
    avatarIcon: '⛰️',
  },
  light: {
    id: 'light',
    name: 'นักเวทแสง',
    title: 'Lumina Archon',
    color: '#eab308',
    badgeBg: 'from-amber-400 to-yellow-600',
    iconName: 'Sun',
    description: 'พลังแห่งรัศมีศักดิ์สิทธิ์ ขจัดความมืดมิด ชำระล้างสิ่งชั่วร้ายด้วยแสงบริสุทธิ์',
    baseStats: { atk: 30, def: 20, mp: 120, manaRegen: 14 },
    specialSkill: 'Divine Aura (+15% Gold & EXP)',
    startingSpellId: 'holylight',
    avatarIcon: '✨',
  },
  dark: {
    id: 'dark',
    name: 'นักเวทความมืด',
    title: 'Umbra Warlock',
    color: '#a855f7',
    badgeBg: 'from-purple-800 to-indigo-950',
    iconName: 'Moon',
    description: 'มนตราเร้นลับจากมิติเงา ควบคุมพลังคำสาปโบราณและกัดกร่อนดวงวิญญาณ',
    baseStats: { atk: 38, def: 12, mp: 115, manaRegen: 9 },
    specialSkill: 'Shadow Drain (+20% Critical Spell Rate)',
    startingSpellId: 'shadowcurse',
    avatarIcon: '🔮',
  },
};

export const SPELLS_CATALOG: Spell[] = [
  {
    id: 'fireball',
    name: 'Fire Ball',
    element: 'fire',
    manaCost: 25,
    damage: 120,
    cooldown: 3,
    reqLevel: 1,
    icon: '🔥',
    description: 'ยิงลูกบอลเพลิงระเบิดใส่ศัตรู สร้างความเสียหายไฟรุนแรง',
    effectType: 'fire',
  },
  {
    id: 'icespike',
    name: 'Ice Spike',
    element: 'water',
    manaCost: 20,
    damage: 95,
    cooldown: 4,
    reqLevel: 2,
    icon: '❄️',
    description: 'เรียกหนามน้ำแข็งแหลมคมแทงจากพื้น แช่แข็งเป้าหมาย',
    effectType: 'ice',
  },
  {
    id: 'windblade',
    name: 'Wind Blade',
    element: 'wind',
    manaCost: 18,
    damage: 85,
    cooldown: 2,
    reqLevel: 3,
    icon: '🌪️',
    description: 'ปล่อยคมมีดสายลมตัดผ่านอากาศ เฉือนศัตรูอย่างรวดเร็ว',
    effectType: 'wind',
  },
  {
    id: 'thunder',
    name: 'Thunder Bolt',
    element: 'earth',
    manaCost: 35,
    damage: 160,
    cooldown: 5,
    reqLevel: 4,
    icon: '⚡',
    description: 'อัศนีบาตผ่าลงมาจากฟากฟ้า พลังทำลายล้างมหาศาล',
    effectType: 'thunder',
  },
  {
    id: 'holylight',
    name: 'Holy Light',
    element: 'light',
    manaCost: 30,
    damage: 140,
    cooldown: 4,
    reqLevel: 5,
    icon: '☀️',
    description: 'ลำแสงศักดิ์สิทธิ์ส่องสว่าง ชำระล้างศัตรูและฟื้นฟูผู้ร่าย',
    effectType: 'light',
  },
  {
    id: 'shadowcurse',
    name: 'Shadow Curse',
    element: 'dark',
    manaCost: 40,
    damage: 200,
    cooldown: 6,
    reqLevel: 6,
    icon: '☠️',
    description: 'เรียกหมอกความมืดมิดแห่งห้วงอเวจี กัดกร่อนศัตรูอย่างรุนแรง',
    effectType: 'shadow',
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  // Wands
  {
    id: 'wand_novice',
    name: 'ไม้กายสิทธิ์โอ๊คโบราณ',
    category: 'wand',
    priceGold: 100,
    priceCrystal: 0,
    reqLevel: 1,
    statBonus: { atk: 10, mp: 20 },
    icon: '🪄',
    description: 'ไม้กายสิทธิ์ทำจากแกนไม้โอ๊คโบราณ เหมาะสำหรับนักเวทเริ่มต้น',
  },
  {
    id: 'wand_crystal',
    name: 'คทาคริสตัลเวทมนตร์',
    category: 'wand',
    priceGold: 350,
    priceCrystal: 5,
    reqLevel: 3,
    statBonus: { atk: 25, mp: 50 },
    icon: '🔮',
    description: 'คทาหัวคริสตัลเปล่งแสง ช่วยรวบรวมมานาและเพิ่มพลังโจมตีเวท',
  },
  {
    id: 'wand_dragon',
    name: 'คทากระดูกมังกรเพลิง',
    category: 'wand',
    priceGold: 800,
    priceCrystal: 15,
    reqLevel: 5,
    statBonus: { atk: 60, mp: 100 },
    icon: '🐉',
    description: 'คทาในตำนานสลักจากศิลาลาวาและเกล็ดมังกรโบราณ',
  },

  // Robes
  {
    id: 'robe_apprentice',
    name: 'เสื้อคลุมนักเรียนฝึกหัด',
    category: 'robe',
    priceGold: 120,
    priceCrystal: 0,
    reqLevel: 1,
    statBonus: { def: 10, mp: 15 },
    icon: '👘',
    description: 'ชุดเสื้อคลุมมาตรฐานของ Arcane Academy เนื้อผ้าทอเวทมนตร์',
  },
  {
    id: 'robe_archmage',
    name: 'เสื้อคลุมกำมะหยี่ทองคำ',
    category: 'robe',
    priceGold: 450,
    priceCrystal: 8,
    reqLevel: 3,
    statBonus: { def: 30, mp: 60 },
    icon: '👗',
    description: 'เสื้อคลุมกำมะหยี่สีน้ำเงินเข้มปักดิ้นทอง สะท้อนเวทมนตร์ได้ดีเยี่ยม',
  },
  {
    id: 'robe_celestial',
    name: 'เสื้อคลุมละอองดวงดาว',
    category: 'robe',
    priceGold: 1000,
    priceCrystal: 20,
    reqLevel: 6,
    statBonus: { def: 65, mp: 140 },
    icon: '🌌',
    description: 'เสื้อคลุมทอจากเส้นใยดวงดาว รัศมีเงางามและปกป้องอย่างสมบูรณ์แบบ',
  },

  // Hats
  {
    id: 'hat_classic',
    name: 'หมวกทรงแหลมคลาสสิก',
    category: 'hat',
    priceGold: 80,
    priceCrystal: 0,
    reqLevel: 1,
    statBonus: { atk: 5, mp: 10 },
    icon: '🧙‍♂️',
    description: 'หมวกพ่อมดทรงยอดนิยม สวมใส่สบาย เสริมสมาธิการร่ายคาถา',
  },
  {
    id: 'hat_starlight',
    name: 'หมวกมงกุฎแสงดารา',
    category: 'hat',
    priceGold: 300,
    priceCrystal: 5,
    reqLevel: 3,
    statBonus: { atk: 18, mp: 40 },
    icon: '👑',
    description: 'มงกุฎเวทประดับอัญมณีดวงดาว เพิ่มพลังจิตอันแข็งแกร่ง',
  },

  // Pets
  {
    id: 'pet_owl',
    name: 'นกฮูกเวทมนตร์พิกเซล',
    category: 'pet',
    priceGold: 250,
    priceCrystal: 3,
    reqLevel: 2,
    statBonus: { mp: 30, atk: 10 },
    icon: '🦉',
    description: 'สัตว์เลี้ยงคู่ใจ ช่วยค้นหาสมบัติและคอยเตือนภัย',
  },
  {
    id: 'pet_dragon',
    name: 'มังกรจิ๋วธาตุไฟ',
    category: 'pet',
    priceGold: 700,
    priceCrystal: 12,
    reqLevel: 5,
    statBonus: { atk: 35, def: 20 },
    icon: '🐲',
    description: 'ลูกมังกรน้อยน่ารัก พ่นเปลวไฟช่วยต่อสู้ตลอดเวลา',
  },

  // Aura Effects
  {
    id: 'aura_sparkle',
    name: 'ออร่าดาวระยิบระยับ',
    category: 'aura',
    priceGold: 200,
    priceCrystal: 2,
    reqLevel: 1,
    statBonus: { mp: 25 },
    icon: '✨',
    description: 'เอฟเฟกต์ละอองดาวส่องประกายรอบตัวละคร',
  },
  {
    id: 'aura_phoenix',
    name: 'ออร่าปีกฟีนิกซ์ทองคำ',
    category: 'aura',
    priceGold: 900,
    priceCrystal: 15,
    reqLevel: 5,
    statBonus: { atk: 40, def: 25 },
    icon: '🔥',
    description: 'ปีกเปลวเพลิงฟีนิกซ์ส่องสว่างไสวแสดงถึงจอมเวทชั้นสูง',
  },
];

export const ACHIEVEMENTS_CATALOG: Achievement[] = [
  {
    id: 'novice_mage',
    title: 'นักเวทมือใหม่',
    description: 'เริ่มต้นเส้นทางใน Arcane Academy และเข้าสู่สถาบัน',
    icon: '🎓',
    reqType: 'level',
    reqValue: 1,
    rewardGold: 100,
    rewardCrystal: 2,
    rewardTitle: 'จอมเวทฝึกหัด',
  },
  {
    id: 'potion_master',
    title: 'นักปรุงยา',
    description: 'ทำภารกิจแก้ปริศนาและตอบคำถามเวทมนตร์สำเร็จ 5 ครั้ง',
    icon: '🧪',
    reqType: 'quests',
    reqValue: 5,
    rewardGold: 250,
    rewardCrystal: 5,
    rewardTitle: 'ผู้เชี่ยวชาญสมุนไพรเวท',
  },
  {
    id: 'explorer',
    title: 'นักสำรวจปราสาท',
    description: 'สะสมทองคำในสถาบันถึง 500 Gold',
    icon: '🏰',
    reqType: 'gold',
    reqValue: 500,
    rewardGold: 300,
    rewardCrystal: 5,
    rewardTitle: 'นักสำรวจปราสาทลอยฟ้า',
  },
  {
    id: 'dungeon_conqueror',
    title: 'ผู้พิชิตดันเจียน',
    description: 'ก้าวสู่อันดับเลเวล 5 และปลดล็อกคาถาใหม่',
    icon: '🗡️',
    reqType: 'level',
    reqValue: 5,
    rewardGold: 600,
    rewardCrystal: 10,
    rewardTitle: 'ผู้พิชิตถ้ำมังกร',
  },
  {
    id: 'grand_archmage',
    title: 'จอมเวทมนตร์',
    description: 'ปลดล็อกคาถาทั้งหมดและมีเลเวลถึง 10ขึ้นไป',
    icon: '👑',
    reqType: 'level',
    reqValue: 10,
    rewardGold: 1500,
    rewardCrystal: 25,
    rewardTitle: 'มหาจอมเวทผู้ยิ่งใหญ่',
  },
];

export const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: 'คาถาใดต่อไปนี้ทำความเสียหายธาตุไฟรุนแรงที่สุด?',
    options: ['Ice Spike', 'Fire Ball', 'Wind Blade', 'Shadow Curse'],
    answerIndex: 1,
    explanation: 'Fire Ball ยิงลูกบอลเพลิงระเบิดสร้างความเสียหายไฟรุนแรง!',
  },
  {
    id: 2,
    question: 'ปราสาทของ Arcane Academy ตั้งอยู่ที่สถานที่ใด?',
    options: ['ถ้ำใต้มหาสมุทร', 'ปราสาทลอยฟ้าเหนือเมฆ', 'ภูเขาหิมะวิเศษ', 'ป่าทึบต้องมนตร์'],
    answerIndex: 1,
    explanation: 'สถาบันเวทมนตร์แห่งนี้ตั้งเด่นสง่าอยู่บนปราสาทลอยฟ้า!',
  },
  {
    id: 3,
    question: 'สายเวทมนตร์ใดที่มีความเชี่ยวชาญด้านการฟื้นฟูและแช่แข็ง?',
    options: ['นักเวทธาตุไฟ', 'นักเวทธาตุน้ำ', 'นักเวทธาตุลม', 'นักเวทความมืด'],
    answerIndex: 1,
    explanation: 'นักเวทธาตุน้ำมีความฟื้นฟู MP สูงและควบคุมสายธารน้ำแข็ง!',
  },
  {
    id: 4,
    question: 'ศิลาเวทมนตร์ Crystal ใช้สำหรับทำอะไรได้บ้าง?',
    options: ['ใช้ซื้อไอเทมระดับสูงในร้านค้า', 'ซ่อมบันได', 'ตกปลาในสระ', 'ไม่สามารถใช้ทำอะไรได้'],
    answerIndex: 0,
    explanation: 'Crystal สามารถใช้ซื้อคทา มงกุฎ สัตว์เลี้ยง และออร่าระดับสูงได้!',
  },
  {
    id: 5,
    question: 'คาถา Holy Light มีคุณสมบัติเด่นในเรื่องใด?',
    options: ['สร้างพายุหมุน', 'ชำระล้างความมืดและฟื้นฟู', 'แช่แข็งศัตรู', 'เรียกอัศนีบาต'],
    answerIndex: 1,
    explanation: 'Holy Light ปล่อยลำแสงศักดิ์สิทธิ์ชำระล้างสิ่งชั่วร้าย!',
  },
];

export const CIPHER_PUZZLES = [
  {
    id: 1,
    scrambled: 'F R I E A B L L',
    answer: 'FIREBALL',
    hint: 'คาถาบอลเพลิงทรงพลัง (F _ R _ B _ L L)',
  },
  {
    id: 2,
    scrambled: 'T H U N E D R',
    answer: 'THUNDER',
    hint: 'อัศนีบาตผ่าฟากฟ้า (T H _ N _ E R)',
  },
  {
    id: 3,
    scrambled: 'A R C A N E',
    answer: 'ARCANE',
    hint: 'ชื่อสถาบันเวทมนตร์แห่งนี้ (A R _ A _ E)',
  },
  {
    id: 4,
    scrambled: 'C R Y S T A L',
    answer: 'CRYSTAL',
    hint: 'ผลึกแก้วเวทมนตร์ล้ำค่า (C R _ S _ A L)',
  },
];
